package demo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SQMsg.proto

public final class SQMsgOuterClass {
  private SQMsgOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SQMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SQMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *��Ϣͷ
     * </pre>
     *
     * <code>int32 StandardHeadr = 1;</code>
     */
    int getStandardHeadr();

    /**
     * <pre>
     *��������ʱ��
     * </pre>
     *
     * <code>string OrigTime = 2;</code>
     */
    String getOrigTime();
    /**
     * <pre>
     *��������ʱ��
     * </pre>
     *
     * <code>string OrigTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrigTimeBytes();

    /**
     * <pre>
     *Ƶ������
     * </pre>
     *
     * <code>int32 ChannelNo = 3;</code>
     */
    int getChannelNo();

    /**
     * <pre>
     *������� 010,020,030,040
     * </pre>
     *
     * <code>int32 MDStreamID = 4;</code>
     */
    int getMDStreamID();

    /**
     * <pre>
     *֤ȯ����
     * </pre>
     *
     * <code>int32 SecurityID = 5;</code>
     */
    int getSecurityID();

    /**
     * <pre>
     *֤ȯ����Դ
     * </pre>
     *
     * <code>int32 SecurityIDSource = 6;</code>
     */
    int getSecurityIDSource();

    /**
     * <pre>
     *��Ʒ�����Ľ��׽׶δ���
     * </pre>
     *
     * <code>string TradingPhaseCode = 7;</code>
     */
    String getTradingPhaseCode();
    /**
     * <pre>
     *��Ʒ�����Ľ��׽׶δ���
     * </pre>
     *
     * <code>string TradingPhaseCode = 7;</code>
     */
    com.google.protobuf.ByteString
        getTradingPhaseCodeBytes();

    /**
     * <pre>
     *���ռ�
     * </pre>
     *
     * <code>double PreClosePx = 8;</code>
     */
    double getPreClosePx();

    /**
     * <pre>
     *�ɽ�����
     * </pre>
     *
     * <code>int32 NumTrades = 9;</code>
     */
    int getNumTrades();

    /**
     * <pre>
     *�ɽ�����
     * </pre>
     *
     * <code>int32 TotalVolumeTrade = 10;</code>
     */
    int getTotalVolumeTrade();

    /**
     * <pre>
     *�ɽ��ܽ��
     * </pre>
     *
     * <code>int32 TotalValueTrade = 11;</code>
     */
    int getTotalValueTrade();
  }
  /**
   * Protobuf type {@code SQMsg}
   */
  public  static final class SQMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SQMsg)
      SQMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SQMsg.newBuilder() to construct.
    private SQMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SQMsg() {
      standardHeadr_ = 0;
      origTime_ = "";
      channelNo_ = 0;
      mDStreamID_ = 0;
      securityID_ = 0;
      securityIDSource_ = 0;
      tradingPhaseCode_ = "";
      preClosePx_ = 0D;
      numTrades_ = 0;
      totalVolumeTrade_ = 0;
      totalValueTrade_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SQMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              standardHeadr_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              origTime_ = s;
              break;
            }
            case 24: {

              channelNo_ = input.readInt32();
              break;
            }
            case 32: {

              mDStreamID_ = input.readInt32();
              break;
            }
            case 40: {

              securityID_ = input.readInt32();
              break;
            }
            case 48: {

              securityIDSource_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              tradingPhaseCode_ = s;
              break;
            }
            case 65: {

              preClosePx_ = input.readDouble();
              break;
            }
            case 72: {

              numTrades_ = input.readInt32();
              break;
            }
            case 80: {

              totalVolumeTrade_ = input.readInt32();
              break;
            }
            case 88: {

              totalValueTrade_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SQMsgOuterClass.internal_static_SQMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SQMsgOuterClass.internal_static_SQMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SQMsg.class, Builder.class);
    }

    public interface CentralizedBiddingSQMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SQMsg.CentralizedBiddingSQMsg)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *������Ŀ����
       * </pre>
       *
       * <code>int32 NoMDEntries = 1;</code>
       */
      int getNoMDEntries();

      /**
       * <pre>
       *������Ŀ���
       * </pre>
       *
       * <code>string MDEtryType = 2;</code>
       */
      String getMDEtryType();
      /**
       * <pre>
       *������Ŀ���
       * </pre>
       *
       * <code>string MDEtryType = 2;</code>
       */
      com.google.protobuf.ByteString
          getMDEtryTypeBytes();

      /**
       * <pre>
       *�۸�
       * </pre>
       *
       * <code>int32 MDEntryPx = 3;</code>
       */
      int getMDEntryPx();

      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>int32 MDEntrySize = 4;</code>
       */
      int getMDEntrySize();

      /**
       * <pre>
       *������λ
       * </pre>
       *
       * <code>int32 MDPriceLevel = 5;</code>
       */
      int getMDPriceLevel();

      /**
       * <pre>
       *��λ��ί�б���
       * </pre>
       *
       * <code>int32 NumberOfOrders = 6;</code>
       */
      int getNumberOfOrders();

      /**
       * <pre>
       *��λ��ʾί�б���
       * </pre>
       *
       * <code>int32 NoOrders = 7;</code>
       */
      int getNoOrders();

      /**
       * <pre>
       *ί������
       * </pre>
       *
       * <code>int32 OrderQty = 8;</code>
       */
      int getOrderQty();
    }
    /**
     * Protobuf type {@code SQMsg.CentralizedBiddingSQMsg}
     */
    public  static final class CentralizedBiddingSQMsg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:SQMsg.CentralizedBiddingSQMsg)
        CentralizedBiddingSQMsgOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CentralizedBiddingSQMsg.newBuilder() to construct.
      private CentralizedBiddingSQMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CentralizedBiddingSQMsg() {
        noMDEntries_ = 0;
        mDEtryType_ = "";
        mDEntryPx_ = 0;
        mDEntrySize_ = 0;
        mDPriceLevel_ = 0;
        numberOfOrders_ = 0;
        noOrders_ = 0;
        orderQty_ = 0;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private CentralizedBiddingSQMsg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                noMDEntries_ = input.readInt32();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                mDEtryType_ = s;
                break;
              }
              case 24: {

                mDEntryPx_ = input.readInt32();
                break;
              }
              case 32: {

                mDEntrySize_ = input.readInt32();
                break;
              }
              case 40: {

                mDPriceLevel_ = input.readInt32();
                break;
              }
              case 48: {

                numberOfOrders_ = input.readInt32();
                break;
              }
              case 56: {

                noOrders_ = input.readInt32();
                break;
              }
              case 64: {

                orderQty_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SQMsgOuterClass.internal_static_SQMsg_CentralizedBiddingSQMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SQMsgOuterClass.internal_static_SQMsg_CentralizedBiddingSQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CentralizedBiddingSQMsg.class, Builder.class);
      }

      public static final int NOMDENTRIES_FIELD_NUMBER = 1;
      private int noMDEntries_;
      /**
       * <pre>
       *������Ŀ����
       * </pre>
       *
       * <code>int32 NoMDEntries = 1;</code>
       */
      public int getNoMDEntries() {
        return noMDEntries_;
      }

      public static final int MDETRYTYPE_FIELD_NUMBER = 2;
      private volatile Object mDEtryType_;
      /**
       * <pre>
       *������Ŀ���
       * </pre>
       *
       * <code>string MDEtryType = 2;</code>
       */
      public String getMDEtryType() {
        Object ref = mDEtryType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mDEtryType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *������Ŀ���
       * </pre>
       *
       * <code>string MDEtryType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMDEtryTypeBytes() {
        Object ref = mDEtryType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mDEtryType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MDENTRYPX_FIELD_NUMBER = 3;
      private int mDEntryPx_;
      /**
       * <pre>
       *�۸�
       * </pre>
       *
       * <code>int32 MDEntryPx = 3;</code>
       */
      public int getMDEntryPx() {
        return mDEntryPx_;
      }

      public static final int MDENTRYSIZE_FIELD_NUMBER = 4;
      private int mDEntrySize_;
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>int32 MDEntrySize = 4;</code>
       */
      public int getMDEntrySize() {
        return mDEntrySize_;
      }

      public static final int MDPRICELEVEL_FIELD_NUMBER = 5;
      private int mDPriceLevel_;
      /**
       * <pre>
       *������λ
       * </pre>
       *
       * <code>int32 MDPriceLevel = 5;</code>
       */
      public int getMDPriceLevel() {
        return mDPriceLevel_;
      }

      public static final int NUMBEROFORDERS_FIELD_NUMBER = 6;
      private int numberOfOrders_;
      /**
       * <pre>
       *��λ��ί�б���
       * </pre>
       *
       * <code>int32 NumberOfOrders = 6;</code>
       */
      public int getNumberOfOrders() {
        return numberOfOrders_;
      }

      public static final int NOORDERS_FIELD_NUMBER = 7;
      private int noOrders_;
      /**
       * <pre>
       *��λ��ʾί�б���
       * </pre>
       *
       * <code>int32 NoOrders = 7;</code>
       */
      public int getNoOrders() {
        return noOrders_;
      }

      public static final int ORDERQTY_FIELD_NUMBER = 8;
      private int orderQty_;
      /**
       * <pre>
       *ί������
       * </pre>
       *
       * <code>int32 OrderQty = 8;</code>
       */
      public int getOrderQty() {
        return orderQty_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (noMDEntries_ != 0) {
          output.writeInt32(1, noMDEntries_);
        }
        if (!getMDEtryTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mDEtryType_);
        }
        if (mDEntryPx_ != 0) {
          output.writeInt32(3, mDEntryPx_);
        }
        if (mDEntrySize_ != 0) {
          output.writeInt32(4, mDEntrySize_);
        }
        if (mDPriceLevel_ != 0) {
          output.writeInt32(5, mDPriceLevel_);
        }
        if (numberOfOrders_ != 0) {
          output.writeInt32(6, numberOfOrders_);
        }
        if (noOrders_ != 0) {
          output.writeInt32(7, noOrders_);
        }
        if (orderQty_ != 0) {
          output.writeInt32(8, orderQty_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (noMDEntries_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, noMDEntries_);
        }
        if (!getMDEtryTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mDEtryType_);
        }
        if (mDEntryPx_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, mDEntryPx_);
        }
        if (mDEntrySize_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, mDEntrySize_);
        }
        if (mDPriceLevel_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, mDPriceLevel_);
        }
        if (numberOfOrders_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, numberOfOrders_);
        }
        if (noOrders_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(7, noOrders_);
        }
        if (orderQty_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, orderQty_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof CentralizedBiddingSQMsg)) {
          return super.equals(obj);
        }
        CentralizedBiddingSQMsg other = (CentralizedBiddingSQMsg) obj;

        boolean result = true;
        result = result && (getNoMDEntries()
            == other.getNoMDEntries());
        result = result && getMDEtryType()
            .equals(other.getMDEtryType());
        result = result && (getMDEntryPx()
            == other.getMDEntryPx());
        result = result && (getMDEntrySize()
            == other.getMDEntrySize());
        result = result && (getMDPriceLevel()
            == other.getMDPriceLevel());
        result = result && (getNumberOfOrders()
            == other.getNumberOfOrders());
        result = result && (getNoOrders()
            == other.getNoOrders());
        result = result && (getOrderQty()
            == other.getOrderQty());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NOMDENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getNoMDEntries();
        hash = (37 * hash) + MDETRYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMDEtryType().hashCode();
        hash = (37 * hash) + MDENTRYPX_FIELD_NUMBER;
        hash = (53 * hash) + getMDEntryPx();
        hash = (37 * hash) + MDENTRYSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getMDEntrySize();
        hash = (37 * hash) + MDPRICELEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getMDPriceLevel();
        hash = (37 * hash) + NUMBEROFORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumberOfOrders();
        hash = (37 * hash) + NOORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getNoOrders();
        hash = (37 * hash) + ORDERQTY_FIELD_NUMBER;
        hash = (53 * hash) + getOrderQty();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static CentralizedBiddingSQMsg parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CentralizedBiddingSQMsg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CentralizedBiddingSQMsg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static CentralizedBiddingSQMsg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static CentralizedBiddingSQMsg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CentralizedBiddingSQMsg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(CentralizedBiddingSQMsg prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SQMsg.CentralizedBiddingSQMsg}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SQMsg.CentralizedBiddingSQMsg)
          CentralizedBiddingSQMsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SQMsgOuterClass.internal_static_SQMsg_CentralizedBiddingSQMsg_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SQMsgOuterClass.internal_static_SQMsg_CentralizedBiddingSQMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CentralizedBiddingSQMsg.class, Builder.class);
        }

        // Construct using SQMsgOuterClass.SQMsg.CentralizedBiddingSQMsg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          noMDEntries_ = 0;

          mDEtryType_ = "";

          mDEntryPx_ = 0;

          mDEntrySize_ = 0;

          mDPriceLevel_ = 0;

          numberOfOrders_ = 0;

          noOrders_ = 0;

          orderQty_ = 0;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SQMsgOuterClass.internal_static_SQMsg_CentralizedBiddingSQMsg_descriptor;
        }

        @Override
        public CentralizedBiddingSQMsg getDefaultInstanceForType() {
          return CentralizedBiddingSQMsg.getDefaultInstance();
        }

        @Override
        public CentralizedBiddingSQMsg build() {
          CentralizedBiddingSQMsg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public CentralizedBiddingSQMsg buildPartial() {
          CentralizedBiddingSQMsg result = new CentralizedBiddingSQMsg(this);
          result.noMDEntries_ = noMDEntries_;
          result.mDEtryType_ = mDEtryType_;
          result.mDEntryPx_ = mDEntryPx_;
          result.mDEntrySize_ = mDEntrySize_;
          result.mDPriceLevel_ = mDPriceLevel_;
          result.numberOfOrders_ = numberOfOrders_;
          result.noOrders_ = noOrders_;
          result.orderQty_ = orderQty_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CentralizedBiddingSQMsg) {
            return mergeFrom((CentralizedBiddingSQMsg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CentralizedBiddingSQMsg other) {
          if (other == CentralizedBiddingSQMsg.getDefaultInstance()) return this;
          if (other.getNoMDEntries() != 0) {
            setNoMDEntries(other.getNoMDEntries());
          }
          if (!other.getMDEtryType().isEmpty()) {
            mDEtryType_ = other.mDEtryType_;
            onChanged();
          }
          if (other.getMDEntryPx() != 0) {
            setMDEntryPx(other.getMDEntryPx());
          }
          if (other.getMDEntrySize() != 0) {
            setMDEntrySize(other.getMDEntrySize());
          }
          if (other.getMDPriceLevel() != 0) {
            setMDPriceLevel(other.getMDPriceLevel());
          }
          if (other.getNumberOfOrders() != 0) {
            setNumberOfOrders(other.getNumberOfOrders());
          }
          if (other.getNoOrders() != 0) {
            setNoOrders(other.getNoOrders());
          }
          if (other.getOrderQty() != 0) {
            setOrderQty(other.getOrderQty());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CentralizedBiddingSQMsg parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CentralizedBiddingSQMsg) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int noMDEntries_ ;
        /**
         * <pre>
         *������Ŀ����
         * </pre>
         *
         * <code>int32 NoMDEntries = 1;</code>
         */
        public int getNoMDEntries() {
          return noMDEntries_;
        }
        /**
         * <pre>
         *������Ŀ����
         * </pre>
         *
         * <code>int32 NoMDEntries = 1;</code>
         */
        public Builder setNoMDEntries(int value) {
          
          noMDEntries_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *������Ŀ����
         * </pre>
         *
         * <code>int32 NoMDEntries = 1;</code>
         */
        public Builder clearNoMDEntries() {
          
          noMDEntries_ = 0;
          onChanged();
          return this;
        }

        private Object mDEtryType_ = "";
        /**
         * <pre>
         *������Ŀ���
         * </pre>
         *
         * <code>string MDEtryType = 2;</code>
         */
        public String getMDEtryType() {
          Object ref = mDEtryType_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            mDEtryType_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *������Ŀ���
         * </pre>
         *
         * <code>string MDEtryType = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMDEtryTypeBytes() {
          Object ref = mDEtryType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            mDEtryType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *������Ŀ���
         * </pre>
         *
         * <code>string MDEtryType = 2;</code>
         */
        public Builder setMDEtryType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          mDEtryType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *������Ŀ���
         * </pre>
         *
         * <code>string MDEtryType = 2;</code>
         */
        public Builder clearMDEtryType() {
          
          mDEtryType_ = getDefaultInstance().getMDEtryType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *������Ŀ���
         * </pre>
         *
         * <code>string MDEtryType = 2;</code>
         */
        public Builder setMDEtryTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          mDEtryType_ = value;
          onChanged();
          return this;
        }

        private int mDEntryPx_ ;
        /**
         * <pre>
         *�۸�
         * </pre>
         *
         * <code>int32 MDEntryPx = 3;</code>
         */
        public int getMDEntryPx() {
          return mDEntryPx_;
        }
        /**
         * <pre>
         *�۸�
         * </pre>
         *
         * <code>int32 MDEntryPx = 3;</code>
         */
        public Builder setMDEntryPx(int value) {
          
          mDEntryPx_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *�۸�
         * </pre>
         *
         * <code>int32 MDEntryPx = 3;</code>
         */
        public Builder clearMDEntryPx() {
          
          mDEntryPx_ = 0;
          onChanged();
          return this;
        }

        private int mDEntrySize_ ;
        /**
         * <pre>
         *����
         * </pre>
         *
         * <code>int32 MDEntrySize = 4;</code>
         */
        public int getMDEntrySize() {
          return mDEntrySize_;
        }
        /**
         * <pre>
         *����
         * </pre>
         *
         * <code>int32 MDEntrySize = 4;</code>
         */
        public Builder setMDEntrySize(int value) {
          
          mDEntrySize_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *����
         * </pre>
         *
         * <code>int32 MDEntrySize = 4;</code>
         */
        public Builder clearMDEntrySize() {
          
          mDEntrySize_ = 0;
          onChanged();
          return this;
        }

        private int mDPriceLevel_ ;
        /**
         * <pre>
         *������λ
         * </pre>
         *
         * <code>int32 MDPriceLevel = 5;</code>
         */
        public int getMDPriceLevel() {
          return mDPriceLevel_;
        }
        /**
         * <pre>
         *������λ
         * </pre>
         *
         * <code>int32 MDPriceLevel = 5;</code>
         */
        public Builder setMDPriceLevel(int value) {
          
          mDPriceLevel_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *������λ
         * </pre>
         *
         * <code>int32 MDPriceLevel = 5;</code>
         */
        public Builder clearMDPriceLevel() {
          
          mDPriceLevel_ = 0;
          onChanged();
          return this;
        }

        private int numberOfOrders_ ;
        /**
         * <pre>
         *��λ��ί�б���
         * </pre>
         *
         * <code>int32 NumberOfOrders = 6;</code>
         */
        public int getNumberOfOrders() {
          return numberOfOrders_;
        }
        /**
         * <pre>
         *��λ��ί�б���
         * </pre>
         *
         * <code>int32 NumberOfOrders = 6;</code>
         */
        public Builder setNumberOfOrders(int value) {
          
          numberOfOrders_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *��λ��ί�б���
         * </pre>
         *
         * <code>int32 NumberOfOrders = 6;</code>
         */
        public Builder clearNumberOfOrders() {
          
          numberOfOrders_ = 0;
          onChanged();
          return this;
        }

        private int noOrders_ ;
        /**
         * <pre>
         *��λ��ʾί�б���
         * </pre>
         *
         * <code>int32 NoOrders = 7;</code>
         */
        public int getNoOrders() {
          return noOrders_;
        }
        /**
         * <pre>
         *��λ��ʾί�б���
         * </pre>
         *
         * <code>int32 NoOrders = 7;</code>
         */
        public Builder setNoOrders(int value) {
          
          noOrders_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *��λ��ʾί�б���
         * </pre>
         *
         * <code>int32 NoOrders = 7;</code>
         */
        public Builder clearNoOrders() {
          
          noOrders_ = 0;
          onChanged();
          return this;
        }

        private int orderQty_ ;
        /**
         * <pre>
         *ί������
         * </pre>
         *
         * <code>int32 OrderQty = 8;</code>
         */
        public int getOrderQty() {
          return orderQty_;
        }
        /**
         * <pre>
         *ί������
         * </pre>
         *
         * <code>int32 OrderQty = 8;</code>
         */
        public Builder setOrderQty(int value) {
          
          orderQty_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *ί������
         * </pre>
         *
         * <code>int32 OrderQty = 8;</code>
         */
        public Builder clearOrderQty() {
          
          orderQty_ = 0;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:SQMsg.CentralizedBiddingSQMsg)
      }

      // @@protoc_insertion_point(class_scope:SQMsg.CentralizedBiddingSQMsg)
      private static final CentralizedBiddingSQMsg DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new CentralizedBiddingSQMsg();
      }

      public static CentralizedBiddingSQMsg getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CentralizedBiddingSQMsg>
          PARSER = new com.google.protobuf.AbstractParser<CentralizedBiddingSQMsg>() {
        @Override
        public CentralizedBiddingSQMsg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CentralizedBiddingSQMsg(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<CentralizedBiddingSQMsg> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<CentralizedBiddingSQMsg> getParserForType() {
        return PARSER;
      }

      @Override
      public CentralizedBiddingSQMsg getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STANDARDHEADR_FIELD_NUMBER = 1;
    private int standardHeadr_;
    /**
     * <pre>
     *��Ϣͷ
     * </pre>
     *
     * <code>int32 StandardHeadr = 1;</code>
     */
    public int getStandardHeadr() {
      return standardHeadr_;
    }

    public static final int ORIGTIME_FIELD_NUMBER = 2;
    private volatile Object origTime_;
    /**
     * <pre>
     *��������ʱ��
     * </pre>
     *
     * <code>string OrigTime = 2;</code>
     */
    public String getOrigTime() {
      Object ref = origTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        origTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��������ʱ��
     * </pre>
     *
     * <code>string OrigTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrigTimeBytes() {
      Object ref = origTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        origTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELNO_FIELD_NUMBER = 3;
    private int channelNo_;
    /**
     * <pre>
     *Ƶ������
     * </pre>
     *
     * <code>int32 ChannelNo = 3;</code>
     */
    public int getChannelNo() {
      return channelNo_;
    }

    public static final int MDSTREAMID_FIELD_NUMBER = 4;
    private int mDStreamID_;
    /**
     * <pre>
     *������� 010,020,030,040
     * </pre>
     *
     * <code>int32 MDStreamID = 4;</code>
     */
    public int getMDStreamID() {
      return mDStreamID_;
    }

    public static final int SECURITYID_FIELD_NUMBER = 5;
    private int securityID_;
    /**
     * <pre>
     *֤ȯ����
     * </pre>
     *
     * <code>int32 SecurityID = 5;</code>
     */
    public int getSecurityID() {
      return securityID_;
    }

    public static final int SECURITYIDSOURCE_FIELD_NUMBER = 6;
    private int securityIDSource_;
    /**
     * <pre>
     *֤ȯ����Դ
     * </pre>
     *
     * <code>int32 SecurityIDSource = 6;</code>
     */
    public int getSecurityIDSource() {
      return securityIDSource_;
    }

    public static final int TRADINGPHASECODE_FIELD_NUMBER = 7;
    private volatile Object tradingPhaseCode_;
    /**
     * <pre>
     *��Ʒ�����Ľ��׽׶δ���
     * </pre>
     *
     * <code>string TradingPhaseCode = 7;</code>
     */
    public String getTradingPhaseCode() {
      Object ref = tradingPhaseCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tradingPhaseCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��Ʒ�����Ľ��׽׶δ���
     * </pre>
     *
     * <code>string TradingPhaseCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTradingPhaseCodeBytes() {
      Object ref = tradingPhaseCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tradingPhaseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRECLOSEPX_FIELD_NUMBER = 8;
    private double preClosePx_;
    /**
     * <pre>
     *���ռ�
     * </pre>
     *
     * <code>double PreClosePx = 8;</code>
     */
    public double getPreClosePx() {
      return preClosePx_;
    }

    public static final int NUMTRADES_FIELD_NUMBER = 9;
    private int numTrades_;
    /**
     * <pre>
     *�ɽ�����
     * </pre>
     *
     * <code>int32 NumTrades = 9;</code>
     */
    public int getNumTrades() {
      return numTrades_;
    }

    public static final int TOTALVOLUMETRADE_FIELD_NUMBER = 10;
    private int totalVolumeTrade_;
    /**
     * <pre>
     *�ɽ�����
     * </pre>
     *
     * <code>int32 TotalVolumeTrade = 10;</code>
     */
    public int getTotalVolumeTrade() {
      return totalVolumeTrade_;
    }

    public static final int TOTALVALUETRADE_FIELD_NUMBER = 11;
    private int totalValueTrade_;
    /**
     * <pre>
     *�ɽ��ܽ��
     * </pre>
     *
     * <code>int32 TotalValueTrade = 11;</code>
     */
    public int getTotalValueTrade() {
      return totalValueTrade_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (standardHeadr_ != 0) {
        output.writeInt32(1, standardHeadr_);
      }
      if (!getOrigTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, origTime_);
      }
      if (channelNo_ != 0) {
        output.writeInt32(3, channelNo_);
      }
      if (mDStreamID_ != 0) {
        output.writeInt32(4, mDStreamID_);
      }
      if (securityID_ != 0) {
        output.writeInt32(5, securityID_);
      }
      if (securityIDSource_ != 0) {
        output.writeInt32(6, securityIDSource_);
      }
      if (!getTradingPhaseCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tradingPhaseCode_);
      }
      if (preClosePx_ != 0D) {
        output.writeDouble(8, preClosePx_);
      }
      if (numTrades_ != 0) {
        output.writeInt32(9, numTrades_);
      }
      if (totalVolumeTrade_ != 0) {
        output.writeInt32(10, totalVolumeTrade_);
      }
      if (totalValueTrade_ != 0) {
        output.writeInt32(11, totalValueTrade_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (standardHeadr_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, standardHeadr_);
      }
      if (!getOrigTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, origTime_);
      }
      if (channelNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, channelNo_);
      }
      if (mDStreamID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mDStreamID_);
      }
      if (securityID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, securityID_);
      }
      if (securityIDSource_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, securityIDSource_);
      }
      if (!getTradingPhaseCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tradingPhaseCode_);
      }
      if (preClosePx_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, preClosePx_);
      }
      if (numTrades_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, numTrades_);
      }
      if (totalVolumeTrade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, totalVolumeTrade_);
      }
      if (totalValueTrade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, totalValueTrade_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SQMsg)) {
        return super.equals(obj);
      }
      SQMsg other = (SQMsg) obj;

      boolean result = true;
      result = result && (getStandardHeadr()
          == other.getStandardHeadr());
      result = result && getOrigTime()
          .equals(other.getOrigTime());
      result = result && (getChannelNo()
          == other.getChannelNo());
      result = result && (getMDStreamID()
          == other.getMDStreamID());
      result = result && (getSecurityID()
          == other.getSecurityID());
      result = result && (getSecurityIDSource()
          == other.getSecurityIDSource());
      result = result && getTradingPhaseCode()
          .equals(other.getTradingPhaseCode());
      result = result && (
          Double.doubleToLongBits(getPreClosePx())
          == Double.doubleToLongBits(
              other.getPreClosePx()));
      result = result && (getNumTrades()
          == other.getNumTrades());
      result = result && (getTotalVolumeTrade()
          == other.getTotalVolumeTrade());
      result = result && (getTotalValueTrade()
          == other.getTotalValueTrade());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STANDARDHEADR_FIELD_NUMBER;
      hash = (53 * hash) + getStandardHeadr();
      hash = (37 * hash) + ORIGTIME_FIELD_NUMBER;
      hash = (53 * hash) + getOrigTime().hashCode();
      hash = (37 * hash) + CHANNELNO_FIELD_NUMBER;
      hash = (53 * hash) + getChannelNo();
      hash = (37 * hash) + MDSTREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getMDStreamID();
      hash = (37 * hash) + SECURITYID_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityID();
      hash = (37 * hash) + SECURITYIDSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityIDSource();
      hash = (37 * hash) + TRADINGPHASECODE_FIELD_NUMBER;
      hash = (53 * hash) + getTradingPhaseCode().hashCode();
      hash = (37 * hash) + PRECLOSEPX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getPreClosePx()));
      hash = (37 * hash) + NUMTRADES_FIELD_NUMBER;
      hash = (53 * hash) + getNumTrades();
      hash = (37 * hash) + TOTALVOLUMETRADE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalVolumeTrade();
      hash = (37 * hash) + TOTALVALUETRADE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalValueTrade();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SQMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SQMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SQMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SQMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SQMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SQMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SQMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SQMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SQMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SQMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SQMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SQMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SQMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SQMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SQMsg)
        SQMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SQMsgOuterClass.internal_static_SQMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SQMsgOuterClass.internal_static_SQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SQMsg.class, Builder.class);
      }

      // Construct using SQMsgOuterClass.SQMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        standardHeadr_ = 0;

        origTime_ = "";

        channelNo_ = 0;

        mDStreamID_ = 0;

        securityID_ = 0;

        securityIDSource_ = 0;

        tradingPhaseCode_ = "";

        preClosePx_ = 0D;

        numTrades_ = 0;

        totalVolumeTrade_ = 0;

        totalValueTrade_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SQMsgOuterClass.internal_static_SQMsg_descriptor;
      }

      @Override
      public SQMsg getDefaultInstanceForType() {
        return SQMsg.getDefaultInstance();
      }

      @Override
      public SQMsg build() {
        SQMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SQMsg buildPartial() {
        SQMsg result = new SQMsg(this);
        result.standardHeadr_ = standardHeadr_;
        result.origTime_ = origTime_;
        result.channelNo_ = channelNo_;
        result.mDStreamID_ = mDStreamID_;
        result.securityID_ = securityID_;
        result.securityIDSource_ = securityIDSource_;
        result.tradingPhaseCode_ = tradingPhaseCode_;
        result.preClosePx_ = preClosePx_;
        result.numTrades_ = numTrades_;
        result.totalVolumeTrade_ = totalVolumeTrade_;
        result.totalValueTrade_ = totalValueTrade_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SQMsg) {
          return mergeFrom((SQMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SQMsg other) {
        if (other == SQMsg.getDefaultInstance()) return this;
        if (other.getStandardHeadr() != 0) {
          setStandardHeadr(other.getStandardHeadr());
        }
        if (!other.getOrigTime().isEmpty()) {
          origTime_ = other.origTime_;
          onChanged();
        }
        if (other.getChannelNo() != 0) {
          setChannelNo(other.getChannelNo());
        }
        if (other.getMDStreamID() != 0) {
          setMDStreamID(other.getMDStreamID());
        }
        if (other.getSecurityID() != 0) {
          setSecurityID(other.getSecurityID());
        }
        if (other.getSecurityIDSource() != 0) {
          setSecurityIDSource(other.getSecurityIDSource());
        }
        if (!other.getTradingPhaseCode().isEmpty()) {
          tradingPhaseCode_ = other.tradingPhaseCode_;
          onChanged();
        }
        if (other.getPreClosePx() != 0D) {
          setPreClosePx(other.getPreClosePx());
        }
        if (other.getNumTrades() != 0) {
          setNumTrades(other.getNumTrades());
        }
        if (other.getTotalVolumeTrade() != 0) {
          setTotalVolumeTrade(other.getTotalVolumeTrade());
        }
        if (other.getTotalValueTrade() != 0) {
          setTotalValueTrade(other.getTotalValueTrade());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SQMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SQMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int standardHeadr_ ;
      /**
       * <pre>
       *��Ϣͷ
       * </pre>
       *
       * <code>int32 StandardHeadr = 1;</code>
       */
      public int getStandardHeadr() {
        return standardHeadr_;
      }
      /**
       * <pre>
       *��Ϣͷ
       * </pre>
       *
       * <code>int32 StandardHeadr = 1;</code>
       */
      public Builder setStandardHeadr(int value) {
        
        standardHeadr_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣͷ
       * </pre>
       *
       * <code>int32 StandardHeadr = 1;</code>
       */
      public Builder clearStandardHeadr() {
        
        standardHeadr_ = 0;
        onChanged();
        return this;
      }

      private Object origTime_ = "";
      /**
       * <pre>
       *��������ʱ��
       * </pre>
       *
       * <code>string OrigTime = 2;</code>
       */
      public String getOrigTime() {
        Object ref = origTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          origTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��������ʱ��
       * </pre>
       *
       * <code>string OrigTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOrigTimeBytes() {
        Object ref = origTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          origTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��������ʱ��
       * </pre>
       *
       * <code>string OrigTime = 2;</code>
       */
      public Builder setOrigTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        origTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������ʱ��
       * </pre>
       *
       * <code>string OrigTime = 2;</code>
       */
      public Builder clearOrigTime() {
        
        origTime_ = getDefaultInstance().getOrigTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������ʱ��
       * </pre>
       *
       * <code>string OrigTime = 2;</code>
       */
      public Builder setOrigTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        origTime_ = value;
        onChanged();
        return this;
      }

      private int channelNo_ ;
      /**
       * <pre>
       *Ƶ������
       * </pre>
       *
       * <code>int32 ChannelNo = 3;</code>
       */
      public int getChannelNo() {
        return channelNo_;
      }
      /**
       * <pre>
       *Ƶ������
       * </pre>
       *
       * <code>int32 ChannelNo = 3;</code>
       */
      public Builder setChannelNo(int value) {
        
        channelNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Ƶ������
       * </pre>
       *
       * <code>int32 ChannelNo = 3;</code>
       */
      public Builder clearChannelNo() {
        
        channelNo_ = 0;
        onChanged();
        return this;
      }

      private int mDStreamID_ ;
      /**
       * <pre>
       *������� 010,020,030,040
       * </pre>
       *
       * <code>int32 MDStreamID = 4;</code>
       */
      public int getMDStreamID() {
        return mDStreamID_;
      }
      /**
       * <pre>
       *������� 010,020,030,040
       * </pre>
       *
       * <code>int32 MDStreamID = 4;</code>
       */
      public Builder setMDStreamID(int value) {
        
        mDStreamID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������� 010,020,030,040
       * </pre>
       *
       * <code>int32 MDStreamID = 4;</code>
       */
      public Builder clearMDStreamID() {
        
        mDStreamID_ = 0;
        onChanged();
        return this;
      }

      private int securityID_ ;
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>int32 SecurityID = 5;</code>
       */
      public int getSecurityID() {
        return securityID_;
      }
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>int32 SecurityID = 5;</code>
       */
      public Builder setSecurityID(int value) {
        
        securityID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>int32 SecurityID = 5;</code>
       */
      public Builder clearSecurityID() {
        
        securityID_ = 0;
        onChanged();
        return this;
      }

      private int securityIDSource_ ;
      /**
       * <pre>
       *֤ȯ����Դ
       * </pre>
       *
       * <code>int32 SecurityIDSource = 6;</code>
       */
      public int getSecurityIDSource() {
        return securityIDSource_;
      }
      /**
       * <pre>
       *֤ȯ����Դ
       * </pre>
       *
       * <code>int32 SecurityIDSource = 6;</code>
       */
      public Builder setSecurityIDSource(int value) {
        
        securityIDSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *֤ȯ����Դ
       * </pre>
       *
       * <code>int32 SecurityIDSource = 6;</code>
       */
      public Builder clearSecurityIDSource() {
        
        securityIDSource_ = 0;
        onChanged();
        return this;
      }

      private Object tradingPhaseCode_ = "";
      /**
       * <pre>
       *��Ʒ�����Ľ��׽׶δ���
       * </pre>
       *
       * <code>string TradingPhaseCode = 7;</code>
       */
      public String getTradingPhaseCode() {
        Object ref = tradingPhaseCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tradingPhaseCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��Ʒ�����Ľ��׽׶δ���
       * </pre>
       *
       * <code>string TradingPhaseCode = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTradingPhaseCodeBytes() {
        Object ref = tradingPhaseCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tradingPhaseCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��Ʒ�����Ľ��׽׶δ���
       * </pre>
       *
       * <code>string TradingPhaseCode = 7;</code>
       */
      public Builder setTradingPhaseCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tradingPhaseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ʒ�����Ľ��׽׶δ���
       * </pre>
       *
       * <code>string TradingPhaseCode = 7;</code>
       */
      public Builder clearTradingPhaseCode() {
        
        tradingPhaseCode_ = getDefaultInstance().getTradingPhaseCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ʒ�����Ľ��׽׶δ���
       * </pre>
       *
       * <code>string TradingPhaseCode = 7;</code>
       */
      public Builder setTradingPhaseCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tradingPhaseCode_ = value;
        onChanged();
        return this;
      }

      private double preClosePx_ ;
      /**
       * <pre>
       *���ռ�
       * </pre>
       *
       * <code>double PreClosePx = 8;</code>
       */
      public double getPreClosePx() {
        return preClosePx_;
      }
      /**
       * <pre>
       *���ռ�
       * </pre>
       *
       * <code>double PreClosePx = 8;</code>
       */
      public Builder setPreClosePx(double value) {
        
        preClosePx_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *���ռ�
       * </pre>
       *
       * <code>double PreClosePx = 8;</code>
       */
      public Builder clearPreClosePx() {
        
        preClosePx_ = 0D;
        onChanged();
        return this;
      }

      private int numTrades_ ;
      /**
       * <pre>
       *�ɽ�����
       * </pre>
       *
       * <code>int32 NumTrades = 9;</code>
       */
      public int getNumTrades() {
        return numTrades_;
      }
      /**
       * <pre>
       *�ɽ�����
       * </pre>
       *
       * <code>int32 NumTrades = 9;</code>
       */
      public Builder setNumTrades(int value) {
        
        numTrades_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ɽ�����
       * </pre>
       *
       * <code>int32 NumTrades = 9;</code>
       */
      public Builder clearNumTrades() {
        
        numTrades_ = 0;
        onChanged();
        return this;
      }

      private int totalVolumeTrade_ ;
      /**
       * <pre>
       *�ɽ�����
       * </pre>
       *
       * <code>int32 TotalVolumeTrade = 10;</code>
       */
      public int getTotalVolumeTrade() {
        return totalVolumeTrade_;
      }
      /**
       * <pre>
       *�ɽ�����
       * </pre>
       *
       * <code>int32 TotalVolumeTrade = 10;</code>
       */
      public Builder setTotalVolumeTrade(int value) {
        
        totalVolumeTrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ɽ�����
       * </pre>
       *
       * <code>int32 TotalVolumeTrade = 10;</code>
       */
      public Builder clearTotalVolumeTrade() {
        
        totalVolumeTrade_ = 0;
        onChanged();
        return this;
      }

      private int totalValueTrade_ ;
      /**
       * <pre>
       *�ɽ��ܽ��
       * </pre>
       *
       * <code>int32 TotalValueTrade = 11;</code>
       */
      public int getTotalValueTrade() {
        return totalValueTrade_;
      }
      /**
       * <pre>
       *�ɽ��ܽ��
       * </pre>
       *
       * <code>int32 TotalValueTrade = 11;</code>
       */
      public Builder setTotalValueTrade(int value) {
        
        totalValueTrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ɽ��ܽ��
       * </pre>
       *
       * <code>int32 TotalValueTrade = 11;</code>
       */
      public Builder clearTotalValueTrade() {
        
        totalValueTrade_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SQMsg)
    }

    // @@protoc_insertion_point(class_scope:SQMsg)
    private static final SQMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SQMsg();
    }

    public static SQMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SQMsg>
        PARSER = new com.google.protobuf.AbstractParser<SQMsg>() {
      @Override
      public SQMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SQMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SQMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SQMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public SQMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SQMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SQMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SQMsg_CentralizedBiddingSQMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SQMsg_CentralizedBiddingSQMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013SQMsg.proto\"\270\003\n\005SQMsg\022\025\n\rStandardHeadr" +
      "\030\001 \001(\005\022\020\n\010OrigTime\030\002 \001(\t\022\021\n\tChannelNo\030\003 " +
      "\001(\005\022\022\n\nMDStreamID\030\004 \001(\005\022\022\n\nSecurityID\030\005 " +
      "\001(\005\022\030\n\020SecurityIDSource\030\006 \001(\005\022\030\n\020Trading" +
      "PhaseCode\030\007 \001(\t\022\022\n\nPreClosePx\030\010 \001(\001\022\021\n\tN" +
      "umTrades\030\t \001(\005\022\030\n\020TotalVolumeTrade\030\n \001(\005" +
      "\022\027\n\017TotalValueTrade\030\013 \001(\005\032\274\001\n\027Centralize" +
      "dBiddingSQMsg\022\023\n\013NoMDEntries\030\001 \001(\005\022\022\n\nMD" +
      "EtryType\030\002 \001(\t\022\021\n\tMDEntryPx\030\003 \001(\005\022\023\n\013MDE" +
      "ntrySize\030\004 \001(\005\022\024\n\014MDPriceLevel\030\005 \001(\005\022\026\n\016" +
      "NumberOfOrders\030\006 \001(\005\022\020\n\010NoOrders\030\007 \001(\005\022\020" +
      "\n\010OrderQty\030\010 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SQMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SQMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SQMsg_descriptor,
        new String[] { "StandardHeadr", "OrigTime", "ChannelNo", "MDStreamID", "SecurityID", "SecurityIDSource", "TradingPhaseCode", "PreClosePx", "NumTrades", "TotalVolumeTrade", "TotalValueTrade", });
    internal_static_SQMsg_CentralizedBiddingSQMsg_descriptor =
      internal_static_SQMsg_descriptor.getNestedTypes().get(0);
    internal_static_SQMsg_CentralizedBiddingSQMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SQMsg_CentralizedBiddingSQMsg_descriptor,
        new String[] { "NoMDEntries", "MDEtryType", "MDEntryPx", "MDEntrySize", "MDPriceLevel", "NumberOfOrders", "NoOrders", "OrderQty", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
