package demo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WriteByWriteQuotationMsg.proto

public final class WriteByWriteQuotationMsg {
  private WriteByWriteQuotationMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WBWQMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WBWQMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *��Ϣͷ
     * </pre>
     *
     * <code>int32 MsgType = 1;</code>
     */
    int getMsgType();

    /**
     * <pre>
     *Ƶ������
     * </pre>
     *
     * <code>int32 ChannelNo = 2;</code>
     */
    int getChannelNo();

    /**
     * <pre>
     *��Ϣ��¼��
     * </pre>
     *
     * <code>int32 AppSeqNum = 3;</code>
     */
    int getAppSeqNum();

    /**
     * <pre>
     *������� 300192
     * </pre>
     *
     * <code>int32 MDStreamID = 4;</code>
     */
    int getMDStreamID();

    /**
     * <pre>
     *֤ȯ����
     * </pre>
     *
     * <code>string SecurityID = 5;</code>
     */
    String getSecurityID();
    /**
     * <pre>
     *֤ȯ����
     * </pre>
     *
     * <code>string SecurityID = 5;</code>
     */
    com.google.protobuf.ByteString
        getSecurityIDBytes();

    /**
     * <pre>
     *֤ȯ����Դ
     * </pre>
     *
     * <code>int32 SecurityIDSource = 6;</code>
     */
    int getSecurityIDSource();

    /**
     * <pre>
     *ί�м۸�
     * </pre>
     *
     * <code>double Price = 7;</code>
     */
    double getPrice();

    /**
     * <pre>
     *ί������
     * </pre>
     *
     * <code>int32 OrderQty = 8;</code>
     */
    int getOrderQty();

    /**
     * <pre>
     *��������
     * </pre>
     *
     * <code>string Side = 9;</code>
     */
    String getSide();
    /**
     * <pre>
     *��������
     * </pre>
     *
     * <code>string Side = 9;</code>
     */
    com.google.protobuf.ByteString
        getSideBytes();

    /**
     * <pre>
     *ί��ʱ��
     * </pre>
     *
     * <code>string TransactTime = 10;</code>
     */
    String getTransactTime();
    /**
     * <pre>
     *ί��ʱ��
     * </pre>
     *
     * <code>string TransactTime = 10;</code>
     */
    com.google.protobuf.ByteString
        getTransactTimeBytes();
  }
  /**
   * Protobuf type {@code WBWQMsg}
   */
  public  static final class WBWQMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WBWQMsg)
      WBWQMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WBWQMsg.newBuilder() to construct.
    private WBWQMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WBWQMsg() {
      msgType_ = 0;
      channelNo_ = 0;
      appSeqNum_ = 0;
      mDStreamID_ = 0;
      securityID_ = "";
      securityIDSource_ = 0;
      price_ = 0D;
      orderQty_ = 0;
      side_ = "";
      transactTime_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WBWQMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgType_ = input.readInt32();
              break;
            }
            case 16: {

              channelNo_ = input.readInt32();
              break;
            }
            case 24: {

              appSeqNum_ = input.readInt32();
              break;
            }
            case 32: {

              mDStreamID_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              securityID_ = s;
              break;
            }
            case 48: {

              securityIDSource_ = input.readInt32();
              break;
            }
            case 57: {

              price_ = input.readDouble();
              break;
            }
            case 64: {

              orderQty_ = input.readInt32();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              side_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              transactTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WriteByWriteQuotationMsg.internal_static_WBWQMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WriteByWriteQuotationMsg.internal_static_WBWQMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WBWQMsg.class, Builder.class);
    }

    public interface CentralizedBiddingWBWQMsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:WBWQMsg.CentralizedBiddingWBWQMsg)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *�������
       * </pre>
       *
       * <code>string OrderType = 1;</code>
       */
      String getOrderType();
      /**
       * <pre>
       *�������
       * </pre>
       *
       * <code>string OrderType = 1;</code>
       */
      com.google.protobuf.ByteString
          getOrderTypeBytes();
    }
    /**
     * Protobuf type {@code WBWQMsg.CentralizedBiddingWBWQMsg}
     */
    public  static final class CentralizedBiddingWBWQMsg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:WBWQMsg.CentralizedBiddingWBWQMsg)
        CentralizedBiddingWBWQMsgOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CentralizedBiddingWBWQMsg.newBuilder() to construct.
      private CentralizedBiddingWBWQMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CentralizedBiddingWBWQMsg() {
        orderType_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private CentralizedBiddingWBWQMsg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();

                orderType_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WriteByWriteQuotationMsg.internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WriteByWriteQuotationMsg.internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CentralizedBiddingWBWQMsg.class, Builder.class);
      }

      public static final int ORDERTYPE_FIELD_NUMBER = 1;
      private volatile Object orderType_;
      /**
       * <pre>
       *�������
       * </pre>
       *
       * <code>string OrderType = 1;</code>
       */
      public String getOrderType() {
        Object ref = orderType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          orderType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *�������
       * </pre>
       *
       * <code>string OrderType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderTypeBytes() {
        Object ref = orderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getOrderTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderType_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getOrderTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof CentralizedBiddingWBWQMsg)) {
          return super.equals(obj);
        }
        CentralizedBiddingWBWQMsg other = (CentralizedBiddingWBWQMsg) obj;

        boolean result = true;
        result = result && getOrderType()
            .equals(other.getOrderType());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getOrderType().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static CentralizedBiddingWBWQMsg parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static CentralizedBiddingWBWQMsg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static CentralizedBiddingWBWQMsg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CentralizedBiddingWBWQMsg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(CentralizedBiddingWBWQMsg prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code WBWQMsg.CentralizedBiddingWBWQMsg}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:WBWQMsg.CentralizedBiddingWBWQMsg)
          CentralizedBiddingWBWQMsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return WriteByWriteQuotationMsg.internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return WriteByWriteQuotationMsg.internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CentralizedBiddingWBWQMsg.class, Builder.class);
        }

        // Construct using WriteByWriteQuotationMsg.WBWQMsg.CentralizedBiddingWBWQMsg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          orderType_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return WriteByWriteQuotationMsg.internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_descriptor;
        }

        @Override
        public CentralizedBiddingWBWQMsg getDefaultInstanceForType() {
          return CentralizedBiddingWBWQMsg.getDefaultInstance();
        }

        @Override
        public CentralizedBiddingWBWQMsg build() {
          CentralizedBiddingWBWQMsg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public CentralizedBiddingWBWQMsg buildPartial() {
          CentralizedBiddingWBWQMsg result = new CentralizedBiddingWBWQMsg(this);
          result.orderType_ = orderType_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CentralizedBiddingWBWQMsg) {
            return mergeFrom((CentralizedBiddingWBWQMsg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CentralizedBiddingWBWQMsg other) {
          if (other == CentralizedBiddingWBWQMsg.getDefaultInstance()) return this;
          if (!other.getOrderType().isEmpty()) {
            orderType_ = other.orderType_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CentralizedBiddingWBWQMsg parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CentralizedBiddingWBWQMsg) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object orderType_ = "";
        /**
         * <pre>
         *�������
         * </pre>
         *
         * <code>string OrderType = 1;</code>
         */
        public String getOrderType() {
          Object ref = orderType_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            orderType_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *�������
         * </pre>
         *
         * <code>string OrderType = 1;</code>
         */
        public com.google.protobuf.ByteString
            getOrderTypeBytes() {
          Object ref = orderType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            orderType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *�������
         * </pre>
         *
         * <code>string OrderType = 1;</code>
         */
        public Builder setOrderType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          orderType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *�������
         * </pre>
         *
         * <code>string OrderType = 1;</code>
         */
        public Builder clearOrderType() {
          
          orderType_ = getDefaultInstance().getOrderType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *�������
         * </pre>
         *
         * <code>string OrderType = 1;</code>
         */
        public Builder setOrderTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          orderType_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:WBWQMsg.CentralizedBiddingWBWQMsg)
      }

      // @@protoc_insertion_point(class_scope:WBWQMsg.CentralizedBiddingWBWQMsg)
      private static final CentralizedBiddingWBWQMsg DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new CentralizedBiddingWBWQMsg();
      }

      public static CentralizedBiddingWBWQMsg getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CentralizedBiddingWBWQMsg>
          PARSER = new com.google.protobuf.AbstractParser<CentralizedBiddingWBWQMsg>() {
        @Override
        public CentralizedBiddingWBWQMsg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CentralizedBiddingWBWQMsg(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<CentralizedBiddingWBWQMsg> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<CentralizedBiddingWBWQMsg> getParserForType() {
        return PARSER;
      }

      @Override
      public CentralizedBiddingWBWQMsg getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <pre>
     *��Ϣͷ
     * </pre>
     *
     * <code>int32 MsgType = 1;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CHANNELNO_FIELD_NUMBER = 2;
    private int channelNo_;
    /**
     * <pre>
     *Ƶ������
     * </pre>
     *
     * <code>int32 ChannelNo = 2;</code>
     */
    public int getChannelNo() {
      return channelNo_;
    }

    public static final int APPSEQNUM_FIELD_NUMBER = 3;
    private int appSeqNum_;
    /**
     * <pre>
     *��Ϣ��¼��
     * </pre>
     *
     * <code>int32 AppSeqNum = 3;</code>
     */
    public int getAppSeqNum() {
      return appSeqNum_;
    }

    public static final int MDSTREAMID_FIELD_NUMBER = 4;
    private int mDStreamID_;
    /**
     * <pre>
     *������� 300192
     * </pre>
     *
     * <code>int32 MDStreamID = 4;</code>
     */
    public int getMDStreamID() {
      return mDStreamID_;
    }

    public static final int SECURITYID_FIELD_NUMBER = 5;
    private volatile Object securityID_;
    /**
     * <pre>
     *֤ȯ����
     * </pre>
     *
     * <code>string SecurityID = 5;</code>
     */
    public String getSecurityID() {
      Object ref = securityID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        securityID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *֤ȯ����
     * </pre>
     *
     * <code>string SecurityID = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSecurityIDBytes() {
      Object ref = securityID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        securityID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITYIDSOURCE_FIELD_NUMBER = 6;
    private int securityIDSource_;
    /**
     * <pre>
     *֤ȯ����Դ
     * </pre>
     *
     * <code>int32 SecurityIDSource = 6;</code>
     */
    public int getSecurityIDSource() {
      return securityIDSource_;
    }

    public static final int PRICE_FIELD_NUMBER = 7;
    private double price_;
    /**
     * <pre>
     *ί�м۸�
     * </pre>
     *
     * <code>double Price = 7;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int ORDERQTY_FIELD_NUMBER = 8;
    private int orderQty_;
    /**
     * <pre>
     *ί������
     * </pre>
     *
     * <code>int32 OrderQty = 8;</code>
     */
    public int getOrderQty() {
      return orderQty_;
    }

    public static final int SIDE_FIELD_NUMBER = 9;
    private volatile Object side_;
    /**
     * <pre>
     *��������
     * </pre>
     *
     * <code>string Side = 9;</code>
     */
    public String getSide() {
      Object ref = side_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        side_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��������
     * </pre>
     *
     * <code>string Side = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSideBytes() {
      Object ref = side_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        side_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTTIME_FIELD_NUMBER = 10;
    private volatile Object transactTime_;
    /**
     * <pre>
     *ί��ʱ��
     * </pre>
     *
     * <code>string TransactTime = 10;</code>
     */
    public String getTransactTime() {
      Object ref = transactTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transactTime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ί��ʱ��
     * </pre>
     *
     * <code>string TransactTime = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTransactTimeBytes() {
      Object ref = transactTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transactTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != 0) {
        output.writeInt32(1, msgType_);
      }
      if (channelNo_ != 0) {
        output.writeInt32(2, channelNo_);
      }
      if (appSeqNum_ != 0) {
        output.writeInt32(3, appSeqNum_);
      }
      if (mDStreamID_ != 0) {
        output.writeInt32(4, mDStreamID_);
      }
      if (!getSecurityIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, securityID_);
      }
      if (securityIDSource_ != 0) {
        output.writeInt32(6, securityIDSource_);
      }
      if (price_ != 0D) {
        output.writeDouble(7, price_);
      }
      if (orderQty_ != 0) {
        output.writeInt32(8, orderQty_);
      }
      if (!getSideBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, side_);
      }
      if (!getTransactTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, transactTime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (channelNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channelNo_);
      }
      if (appSeqNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, appSeqNum_);
      }
      if (mDStreamID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, mDStreamID_);
      }
      if (!getSecurityIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, securityID_);
      }
      if (securityIDSource_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, securityIDSource_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, price_);
      }
      if (orderQty_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, orderQty_);
      }
      if (!getSideBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, side_);
      }
      if (!getTransactTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, transactTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WBWQMsg)) {
        return super.equals(obj);
      }
      WBWQMsg other = (WBWQMsg) obj;

      boolean result = true;
      result = result && (getMsgType()
          == other.getMsgType());
      result = result && (getChannelNo()
          == other.getChannelNo());
      result = result && (getAppSeqNum()
          == other.getAppSeqNum());
      result = result && (getMDStreamID()
          == other.getMDStreamID());
      result = result && getSecurityID()
          .equals(other.getSecurityID());
      result = result && (getSecurityIDSource()
          == other.getSecurityIDSource());
      result = result && (
          Double.doubleToLongBits(getPrice())
          == Double.doubleToLongBits(
              other.getPrice()));
      result = result && (getOrderQty()
          == other.getOrderQty());
      result = result && getSide()
          .equals(other.getSide());
      result = result && getTransactTime()
          .equals(other.getTransactTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + CHANNELNO_FIELD_NUMBER;
      hash = (53 * hash) + getChannelNo();
      hash = (37 * hash) + APPSEQNUM_FIELD_NUMBER;
      hash = (53 * hash) + getAppSeqNum();
      hash = (37 * hash) + MDSTREAMID_FIELD_NUMBER;
      hash = (53 * hash) + getMDStreamID();
      hash = (37 * hash) + SECURITYID_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityID().hashCode();
      hash = (37 * hash) + SECURITYIDSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSecurityIDSource();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + ORDERQTY_FIELD_NUMBER;
      hash = (53 * hash) + getOrderQty();
      hash = (37 * hash) + SIDE_FIELD_NUMBER;
      hash = (53 * hash) + getSide().hashCode();
      hash = (37 * hash) + TRANSACTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getTransactTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WBWQMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WBWQMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WBWQMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WBWQMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WBWQMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WBWQMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WBWQMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WBWQMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static WBWQMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static WBWQMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WBWQMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WBWQMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WBWQMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WBWQMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WBWQMsg)
        WBWQMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WriteByWriteQuotationMsg.internal_static_WBWQMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WriteByWriteQuotationMsg.internal_static_WBWQMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WBWQMsg.class, Builder.class);
      }

      // Construct using WriteByWriteQuotationMsg.WBWQMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        channelNo_ = 0;

        appSeqNum_ = 0;

        mDStreamID_ = 0;

        securityID_ = "";

        securityIDSource_ = 0;

        price_ = 0D;

        orderQty_ = 0;

        side_ = "";

        transactTime_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WriteByWriteQuotationMsg.internal_static_WBWQMsg_descriptor;
      }

      @Override
      public WBWQMsg getDefaultInstanceForType() {
        return WBWQMsg.getDefaultInstance();
      }

      @Override
      public WBWQMsg build() {
        WBWQMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public WBWQMsg buildPartial() {
        WBWQMsg result = new WBWQMsg(this);
        result.msgType_ = msgType_;
        result.channelNo_ = channelNo_;
        result.appSeqNum_ = appSeqNum_;
        result.mDStreamID_ = mDStreamID_;
        result.securityID_ = securityID_;
        result.securityIDSource_ = securityIDSource_;
        result.price_ = price_;
        result.orderQty_ = orderQty_;
        result.side_ = side_;
        result.transactTime_ = transactTime_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WBWQMsg) {
          return mergeFrom((WBWQMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WBWQMsg other) {
        if (other == WBWQMsg.getDefaultInstance()) return this;
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (other.getChannelNo() != 0) {
          setChannelNo(other.getChannelNo());
        }
        if (other.getAppSeqNum() != 0) {
          setAppSeqNum(other.getAppSeqNum());
        }
        if (other.getMDStreamID() != 0) {
          setMDStreamID(other.getMDStreamID());
        }
        if (!other.getSecurityID().isEmpty()) {
          securityID_ = other.securityID_;
          onChanged();
        }
        if (other.getSecurityIDSource() != 0) {
          setSecurityIDSource(other.getSecurityIDSource());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getOrderQty() != 0) {
          setOrderQty(other.getOrderQty());
        }
        if (!other.getSide().isEmpty()) {
          side_ = other.side_;
          onChanged();
        }
        if (!other.getTransactTime().isEmpty()) {
          transactTime_ = other.transactTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WBWQMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WBWQMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       *��Ϣͷ
       * </pre>
       *
       * <code>int32 MsgType = 1;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       *��Ϣͷ
       * </pre>
       *
       * <code>int32 MsgType = 1;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣͷ
       * </pre>
       *
       * <code>int32 MsgType = 1;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private int channelNo_ ;
      /**
       * <pre>
       *Ƶ������
       * </pre>
       *
       * <code>int32 ChannelNo = 2;</code>
       */
      public int getChannelNo() {
        return channelNo_;
      }
      /**
       * <pre>
       *Ƶ������
       * </pre>
       *
       * <code>int32 ChannelNo = 2;</code>
       */
      public Builder setChannelNo(int value) {
        
        channelNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Ƶ������
       * </pre>
       *
       * <code>int32 ChannelNo = 2;</code>
       */
      public Builder clearChannelNo() {
        
        channelNo_ = 0;
        onChanged();
        return this;
      }

      private int appSeqNum_ ;
      /**
       * <pre>
       *��Ϣ��¼��
       * </pre>
       *
       * <code>int32 AppSeqNum = 3;</code>
       */
      public int getAppSeqNum() {
        return appSeqNum_;
      }
      /**
       * <pre>
       *��Ϣ��¼��
       * </pre>
       *
       * <code>int32 AppSeqNum = 3;</code>
       */
      public Builder setAppSeqNum(int value) {
        
        appSeqNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ��¼��
       * </pre>
       *
       * <code>int32 AppSeqNum = 3;</code>
       */
      public Builder clearAppSeqNum() {
        
        appSeqNum_ = 0;
        onChanged();
        return this;
      }

      private int mDStreamID_ ;
      /**
       * <pre>
       *������� 300192
       * </pre>
       *
       * <code>int32 MDStreamID = 4;</code>
       */
      public int getMDStreamID() {
        return mDStreamID_;
      }
      /**
       * <pre>
       *������� 300192
       * </pre>
       *
       * <code>int32 MDStreamID = 4;</code>
       */
      public Builder setMDStreamID(int value) {
        
        mDStreamID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������� 300192
       * </pre>
       *
       * <code>int32 MDStreamID = 4;</code>
       */
      public Builder clearMDStreamID() {
        
        mDStreamID_ = 0;
        onChanged();
        return this;
      }

      private Object securityID_ = "";
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>string SecurityID = 5;</code>
       */
      public String getSecurityID() {
        Object ref = securityID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          securityID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>string SecurityID = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSecurityIDBytes() {
        Object ref = securityID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          securityID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>string SecurityID = 5;</code>
       */
      public Builder setSecurityID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        securityID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>string SecurityID = 5;</code>
       */
      public Builder clearSecurityID() {
        
        securityID_ = getDefaultInstance().getSecurityID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *֤ȯ����
       * </pre>
       *
       * <code>string SecurityID = 5;</code>
       */
      public Builder setSecurityIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        securityID_ = value;
        onChanged();
        return this;
      }

      private int securityIDSource_ ;
      /**
       * <pre>
       *֤ȯ����Դ
       * </pre>
       *
       * <code>int32 SecurityIDSource = 6;</code>
       */
      public int getSecurityIDSource() {
        return securityIDSource_;
      }
      /**
       * <pre>
       *֤ȯ����Դ
       * </pre>
       *
       * <code>int32 SecurityIDSource = 6;</code>
       */
      public Builder setSecurityIDSource(int value) {
        
        securityIDSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *֤ȯ����Դ
       * </pre>
       *
       * <code>int32 SecurityIDSource = 6;</code>
       */
      public Builder clearSecurityIDSource() {
        
        securityIDSource_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <pre>
       *ί�м۸�
       * </pre>
       *
       * <code>double Price = 7;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <pre>
       *ί�м۸�
       * </pre>
       *
       * <code>double Price = 7;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ί�м۸�
       * </pre>
       *
       * <code>double Price = 7;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private int orderQty_ ;
      /**
       * <pre>
       *ί������
       * </pre>
       *
       * <code>int32 OrderQty = 8;</code>
       */
      public int getOrderQty() {
        return orderQty_;
      }
      /**
       * <pre>
       *ί������
       * </pre>
       *
       * <code>int32 OrderQty = 8;</code>
       */
      public Builder setOrderQty(int value) {
        
        orderQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ί������
       * </pre>
       *
       * <code>int32 OrderQty = 8;</code>
       */
      public Builder clearOrderQty() {
        
        orderQty_ = 0;
        onChanged();
        return this;
      }

      private Object side_ = "";
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>string Side = 9;</code>
       */
      public String getSide() {
        Object ref = side_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          side_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>string Side = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSideBytes() {
        Object ref = side_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          side_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>string Side = 9;</code>
       */
      public Builder setSide(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        side_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>string Side = 9;</code>
       */
      public Builder clearSide() {
        
        side_ = getDefaultInstance().getSide();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>string Side = 9;</code>
       */
      public Builder setSideBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        side_ = value;
        onChanged();
        return this;
      }

      private Object transactTime_ = "";
      /**
       * <pre>
       *ί��ʱ��
       * </pre>
       *
       * <code>string TransactTime = 10;</code>
       */
      public String getTransactTime() {
        Object ref = transactTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          transactTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ί��ʱ��
       * </pre>
       *
       * <code>string TransactTime = 10;</code>
       */
      public com.google.protobuf.ByteString
          getTransactTimeBytes() {
        Object ref = transactTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          transactTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ί��ʱ��
       * </pre>
       *
       * <code>string TransactTime = 10;</code>
       */
      public Builder setTransactTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transactTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ί��ʱ��
       * </pre>
       *
       * <code>string TransactTime = 10;</code>
       */
      public Builder clearTransactTime() {
        
        transactTime_ = getDefaultInstance().getTransactTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ί��ʱ��
       * </pre>
       *
       * <code>string TransactTime = 10;</code>
       */
      public Builder setTransactTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transactTime_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WBWQMsg)
    }

    // @@protoc_insertion_point(class_scope:WBWQMsg)
    private static final WBWQMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WBWQMsg();
    }

    public static WBWQMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WBWQMsg>
        PARSER = new com.google.protobuf.AbstractParser<WBWQMsg>() {
      @Override
      public WBWQMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WBWQMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WBWQMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<WBWQMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public WBWQMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WBWQMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WBWQMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036WriteByWriteQuotationMsg.proto\"\367\001\n\007WBW" +
      "QMsg\022\017\n\007MsgType\030\001 \001(\005\022\021\n\tChannelNo\030\002 \001(\005" +
      "\022\021\n\tAppSeqNum\030\003 \001(\005\022\022\n\nMDStreamID\030\004 \001(\005\022" +
      "\022\n\nSecurityID\030\005 \001(\t\022\030\n\020SecurityIDSource\030" +
      "\006 \001(\005\022\r\n\005Price\030\007 \001(\001\022\020\n\010OrderQty\030\010 \001(\005\022\014" +
      "\n\004Side\030\t \001(\t\022\024\n\014TransactTime\030\n \001(\t\032.\n\031Ce" +
      "ntralizedBiddingWBWQMsg\022\021\n\tOrderType\030\001 \001" +
      "(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WBWQMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WBWQMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WBWQMsg_descriptor,
        new String[] { "MsgType", "ChannelNo", "AppSeqNum", "MDStreamID", "SecurityID", "SecurityIDSource", "Price", "OrderQty", "Side", "TransactTime", });
    internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_descriptor =
      internal_static_WBWQMsg_descriptor.getNestedTypes().get(0);
    internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WBWQMsg_CentralizedBiddingWBWQMsg_descriptor,
        new String[] { "OrderType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
